### PR TITLE
Add unit test for marshall to cover KeyError exception

### PR DESCRIPTION
**Pull request by fredthomsen**
Unit test to cover KeyError in marshal as mentioned in #1.

### CODE REVIEW

**Comment by TimDaub** [comment]
Hey @fredthomsen, thank you for your contribution! :tada:

**Comment by TimDaub** [comment]
@fredthomsen I've made a small mistake in simply merging your pull request.

We want to make sure that all the code contained in this repository is explicitly released under the underlying license (MIT).

Since we didn’t ask you to sign a Contributor Licensing Agreement before we merged, we now have code in the repository you hold all the intellectual property rights to, which could cause trouble for people using this library if you decided to enforce your rights later.

In order to get your code licensed properly into this repository, one of the following needs to happen:
1. You sign a CLA here (https://www.bigchaindb.com/cla/), and reply to confirm that you intend it to cover your PR, along with a link to the PR; or
2. The following process:
- I'll remove your code with this PR from the repository
- You create another PR with your code
- I'll ask you to sign our CLA (https://www.bigchaindb.com/cla/) and confirm with a comment in your pull request containing a block of text.
- Once you've signed it and confirmed, I'll accept your pull requests and we'll all be happy :tada: 

Sorry for the inconvenience and thanks again for your PR!

**Comment by fredthomsen** [comment]
My secret evil plan has been ruined :grin: I accepted your agreement online.  I see the code is still in the repo.  Do you still need another pull request?

**Comment by fredthomsen** [comment]
This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so. Moreover, I intend for my agreement and acceptance to cover all my contributions in this pull request ( https://github.com/bigchaindb/py-ipld/pull/7 ), including those made before I clicked to accept the agreement.

tIsgd7JwupIDRzcR4lOcOz0nIZl16VYNHigp3Y7J2TxJs0X83UKfOGAlEPdTA9o

**Comment by ttmc** [comment]
Thanks @fredthomsen :+1:

**Pull request merged**
